FROM python:3.9-slim

# Install dependencies
RUN apt-get update && apt-get install -y tor && pip install PyQt5 websockets requests beautifulsoup4 python-magic-bin ipfshttpclient tweepy flask stem

# Copy project files
COPY . /app

# Set working directory
WORKDIR /app

# Default command
CMD ["python", "bunkerbuster.py"]